(function(){const API_URL="https://sub-culture-ai-voice.crocolungs.workers.dev/chat";let history=[],recognition=null,listening=false;
const s=document.createElement("style");s.textContent=`#sc-ai-button{position:fixed;right:22px;bottom:22px;z-index:99999;border:0;border-radius:999px;background:#0E0E0E;color:#fff;padding:14px 18px;font:700 14px Arial;cursor:pointer;box-shadow:0 8px 30px rgba(0,0,0,.22)}#sc-ai-panel{position:fixed;right:22px;bottom:82px;z-index:99999;width:min(390px,calc(100vw - 30px));height:min(590px,calc(100vh - 110px));display:none;flex-direction:column;overflow:hidden;background:#fff;border:1px solid #ddd;border-radius:18px;box-shadow:0 18px 60px rgba(0,0,0,.25);font-family:Arial}#sc-ai-panel.sc-open{display:flex}.sc-ai-head{display:flex;justify-content:space-between;padding:16px 18px;background:#0E0E0E;color:#fff}.sc-ai-title{font-weight:800}.sc-ai-subtitle{margin-top:3px;font-size:11px;opacity:.72}.sc-ai-close{border:0;background:transparent;color:#fff;font-size:24px;cursor:pointer}#sc-ai-messages{flex:1;overflow-y:auto;padding:16px;background:#f1f0ee}.sc-ai-msg{max-width:86%;margin:0 0 10px;padding:10px 12px;border-radius:14px;font-size:14px;line-height:1.45;white-space:pre-wrap;overflow-wrap:anywhere}.sc-ai-user{margin-left:auto;background:#0E0E0E;color:#fff}.sc-ai-assistant{background:#fff;color:#111}.sc-ai-status{min-height:18px;padding:6px 14px 0;color:#666;font-size:11px;background:#fff}.sc-ai-controls{display:flex;gap:8px;padding:10px;border-top:1px solid #ddd;background:#fff}#sc-ai-input{flex:1;min-width:0;resize:none;height:42px;padding:11px 12px;box-sizing:border-box;border:1px solid #ccc;border-radius:10px;font:14px Arial}.sc-ai-action{width:44px;height:42px;border:0;border-radius:10px;cursor:pointer;background:#0E0E0E;color:#fff}.sc-ai-send{width:auto;padding:0 14px;font-size:13px;font-weight:700}.sc-ai-action:disabled{opacity:.45}.sc-ai-footer{display:flex;justify-content:space-between;padding:8px 12px 10px;background:#fff;color:#777;font-size:10px}.sc-ai-stop{border:0;background:transparent;color:#555;cursor:pointer}@media(max-width:600px){#sc-ai-button{right:14px;bottom:14px}#sc-ai-panel{right:10px;bottom:70px;width:calc(100vw - 20px)}}`;document.head.appendChild(s);
const b=document.createElement("button");b.id="sc-ai-button";b.type="button";b.textContent="🤖 Sub Culture AI";
const panel=document.createElement("section");panel.id="sc-ai-panel";panel.innerHTML=`<div class="sc-ai-head"><div><div class="sc-ai-title">Sub Culture AI</div><div class="sc-ai-subtitle">Ask by text or voice</div></div><button class="sc-ai-close" type="button">×</button></div><div id="sc-ai-messages"></div><div class="sc-ai-status" id="sc-ai-status"></div><div class="sc-ai-controls"><textarea id="sc-ai-input" placeholder="Ask Sub Culture AI..."></textarea><button class="sc-ai-action" id="sc-ai-mic">🎙️</button><button class="sc-ai-action sc-ai-send" id="sc-ai-send">Send</button></div><div class="sc-ai-footer"><span>Voice replies use your browser.</span><button class="sc-ai-stop" id="sc-ai-stop">Stop voice</button></div>`;
document.body.append(b,panel);
const m=document.getElementById("sc-ai-messages"),i=document.getElementById("sc-ai-input"),mic=document.getElementById("sc-ai-mic"),send=document.getElementById("sc-ai-send"),status=document.getElementById("sc-ai-status");
function add(r,t){const d=document.createElement("div");d.className="sc-ai-msg "+(r==="user"?"sc-ai-user":"sc-ai-assistant");d.textContent=t;m.appendChild(d);m.scrollTop=m.scrollHeight}
function speak(t){if(!speechSynthesis)return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang="en-ZA";speechSynthesis.speak(u)}
async function ask(t){t=(t||"").trim();if(!t)return;add("user",t);i.value="";history.push({role:"user",content:t});history=history.slice(-10);status.textContent="Thinking...";send.disabled=mic.disabled=true;try{const r=await fetch(API_URL,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({messages:history})});const d=await r.json();if(!r.ok||!d.ok)throw Error();const a=String(d.answer||"I couldn't generate a response right now.");add("assistant",a);history.push({role:"assistant",content:a});history=history.slice(-10);status.textContent="";speak(a)}catch(e){add("assistant","Sorry, I couldn't connect to Sub Culture AI right now.");status.textContent=""}finally{send.disabled=mic.disabled=false}}
const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(SR){recognition=new SR();recognition.lang="en-ZA";recognition.continuous=false;recognition.onstart=()=>{listening=true;mic.textContent="⏹";status.textContent="Listening..."};recognition.onresult=e=>ask(e.results[0][0].transcript);recognition.onend=()=>{listening=false;mic.textContent="🎙️";if(status.textContent==="Listening...")status.textContent=""};recognition.onerror=()=>{listening=false;mic.textContent="🎙️";status.textContent="Microphone input was not available."}}else mic.disabled=true;
b.onclick=()=>{panel.classList.toggle("sc-open");if(panel.classList.contains("sc-open")){if(!m.children.length)add("assistant","Hi. I'm Sub Culture AI. Ask me about the website, articles, photography, downloads, trivia or the community.");i.focus()}};
panel.querySelector(".sc-ai-close").onclick=()=>panel.classList.remove("sc-open");send.onclick=()=>ask(i.value);i.onkeydown=e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();ask(i.value)}};mic.onclick=()=>{if(!recognition)return;if(listening)recognition.stop();else try{recognition.start()}catch(e){}};document.getElementById("sc-ai-stop").onclick=()=>speechSynthesis&&speechSynthesis.cancel()})();

