(function(){'use strict';
var W='https://sub-culture-ai-voice.crocolungs.workers.dev/chat';var r=null;
var s=document.createElement('style');s.textContent='#scai{position:fixed;right:20px;bottom:20px;z-index:9998;font-family:Work Sans,Arial,sans-serif}#scai-toggle{width:60px;height:60px;border:0;border-radius:50%;background:#111;color:#fff;font-size:24px;cursor:pointer;box-shadow:0 8px 28px #0004}#scai-panel{display:none;width:min(380px,calc(100vw - 28px));background:#fff;color:#111;border-radius:16px;box-shadow:0 15px 50px #0004;overflow:hidden;margin-bottom:12px}#scai-panel.open{display:block}.scai-head{background:#111;color:#fff;padding:15px 17px;display:flex;justify-content:space-between}.scai-head strong{font-size:16px}.scai-head small{display:block;opacity:.7;margin-top:3px}#scai-close{background:none;border:0;color:#fff;font-size:22px;cursor:pointer}.scai-body{padding:14px}.scai-log{height:250px;overflow:auto;background:#f5f5f3;border-radius:10px;padding:10px}.scai-msg{margin:0 0 9px;padding:9px 11px;border-radius:10px;line-height:1.45;font-size:14px;white-space:pre-wrap}.scai-user{background:#111;color:#fff;margin-left:28px}.scai-bot{background:#fff;border:1px solid #ddd;margin-right:20px}.scai-controls{display:flex;gap:7px;margin-top:9px}.scai-input{flex:1;min-width:0;border:1px solid #ccc;border-radius:9px;padding:9px;font:inherit;resize:none}.scai-btn{border:0;border-radius:9px;padding:9px 11px;background:#111;color:#fff;cursor:pointer}.scai-btn.active{background:#c62828}.scai-tools{display:flex;justify-content:space-between;margin-top:7px;font-size:12px;color:#666}#scai-stop{display:none;border:0;background:none;color:#900;cursor:pointer}';document.head.appendChild(s);
var d=document.createElement('div');d.id='scai';d.innerHTML='<div id="scai-panel" role="dialog" aria-label="Sub Culture AI Assistant"><div class="scai-head"><div><strong>Sub Culture AI</strong><small>Ask by voice or text</small></div><button id="scai-close">×</button></div><div class="scai-body"><div class="scai-log" id="scai-log"><div class="scai-msg scai-bot">Hi. I\'m the Sub Culture AI Assistant. Ask me about the site, articles, music, photography, downloads, trivia or community.</div></div><div class="scai-controls"><textarea id="scai-input" class="scai-input" rows="2" placeholder="Ask something…"></textarea><button id="scai-send" class="scai-btn">Send</button><button id="scai-mic" class="scai-btn" aria-label="Speak">🎙️</button></div><div class="scai-tools"><span id="scai-status">Ready</span><button id="scai-stop">Stop voice</button></div></div></div><button id="scai-toggle" aria-label="Open Sub Culture AI">🎙️</button>';document.body.appendChild(d);
var panel=d.querySelector('#scai-panel'),input=d.querySelector('#scai-input'),log=d.querySelector('#scai-log'),status=d.querySelector('#scai-status'),mic=d.querySelector('#scai-mic'),history=[];
function add(t,c){var x=document.createElement('div');x.className='scai-msg '+(c==='user'?'scai-user':'scai-bot');x.textContent=t;log.appendChild(x);log.scrollTop=log.scrollHeight}
function speak(t){if(!speechSynthesis)return;speechSynthesis.cancel();var u=new SpeechSynthesisUtterance(t);u.rate=1;u.onstart=function(){d.querySelector('#scai-stop').style.display='inline'};u.onend=function(){d.querySelector('#scai-stop').style.display='none'};speechSynthesis.speak(u)}
async function ask(t){t=t.trim();if(!t)return;add(t,'user');input.value='';status.textContent='Thinking…';history.push({role:'user',content:t});try{var q=await fetch(W,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages:history.slice(-10)})}),j=await q.json();if(!q.ok||!j.ok)throw Error(j.error||'Unavailable');var a=j.answer||'I could not answer that right now.';history.push({role:'assistant',content:a});add(a,'assistant');speak(a);status.textContent='Ready'}catch(e){add('Sorry, I could not connect to the AI assistant. Please try again.','assistant');status.textContent='Connection problem'}input.focus()}
d.querySelector('#scai-toggle').onclick=function(){panel.classList.toggle('open');if(panel.classList.contains('open'))input.focus()};d.querySelector('#scai-close').onclick=function(){panel.classList.remove('open')};d.querySelector('#scai-send').onclick=function(){ask(input.value)};input.onkeydown=function(e){if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();ask(input.value)}};
mic.onclick=function(){var SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){status.textContent='Voice input is not supported here. Type instead.';return}r=new SR();r.lang='en-ZA';r.interimResults=false;r.maxAlternatives=1;r.onstart=function(){mic.classList.add('active');status.textContent='Listening…'};r.onresult=function(e){var t=e.results[0][0].transcript;input.value=t;ask(t)};r.onerror=function(){status.textContent='Voice input stopped';mic.classList.remove('active')};r.onend=function(){mic.classList.remove('active');if(status.textContent==='Listening…')status.textContent='Ready'};r.start()};d.querySelector('#scai-stop').onclick=function(){if(speechSynthesis)speechSynthesis.cancel();this.style.display='none';status.textContent='Ready'};
})();
